# help_content.py

HELP_TITLE = "LIMbo Help"

HELP_MONITOR_TEXT = [
    "---------------------------------------------------------",
    "  LIMbo - <c2>Light Intuitive Monitor.</> <c1>Blessed.</> <c4>Obscured.</>",
    "---------------------------------------------------------",
    "",
    "<b5>======= General Keys (Interactive Mode) =======</>",
    " <c3>[q]uit</>         : Exit the monitor",
    " <c3>[h]elp</>         : Show this help screen",
    " <c3>[r]efresh</>      : Force refresh Docker cache",
    "",
    "<b5>====== Modes (Toggle Keys) ======</>",
    " <c1>[d]ocker</>        : Toggle Docker mode (show only container processes)",
    " <c4>[k]iller</>        : Toggle Killer mode (select process to signal)",
    "  Normal Mode : Default view, shows all processes.",
    "",
    "<b5>== Process List Navigation ==</>",
    " <c3>[Up]/[Down]</>    : Move selection up/down by one line",
    " <c3>[PgUp]/[PgDn]</> : Move selection up/down by one page",
    " <c3>[Home]/[End]</>  : Move selection to the top/bottom of the list",
    " <c3>Mouse Click</>    : Select process under cursor",
    "",
    "<b5>====== Process Sorting ======</>",
    " <c3>[Tab]</>          : Cycle sort key forward",
    " <c3>[Shift+Tab]</>    : Cycle sort key backward",
    "              : (Order: RSS->CPU->MEM%->PID->VMS->Name)",
    " <c3>[r]ss</>          : Sort by Resident Set Size (Memory)",
    " <c3>[c]pu</>          : Sort by CPU Percentage",
    " <c3>[m]emory</>       : Sort by Memory Percentage",
    " <c3>[p]id</>          : Sort by Process ID",
    " <c3>[v]ms</>          : Sort by Virtual Memory Size",
    " <c3>[n]ame</>         : Sort by Process Display Name",
    " * Changing sort resets selection.",
    "",
    "<b5>== Actions (Press <c3>Enter</>/<c3>Return</> on Selected Process) ==</>",
    "  Normal Mode : Show detailed process information",
    " <c1>Docker Mode</> : Show Docker action menu ([I]nspect, [R]estart, [S]hell cmd)",
    " <c4>Killer Mode</> : Show signal confirmation ([S]igTERM, [K]ill -9)",
    "",
    "<b5>======== Other ========</>",
    "  Cache Files    : /tmp/py_monitor_prev_rss.*.tsv",
    "                 : /tmp/docker_name_cache.tsv",
    "  Log File       : /tmp/py_monitor_errors.log",
]

HELP_CLI_TEXT = [
    "<b5>====== Навигационный TUI ======</>",
    " <c3>lim tui</> (или <c3>list</c3>, <c3>nav</c3>, <c3>l</c3>)",
    "  Запускает интерактивный TUI для навигации по контейнерам и закладкам.",
    "",
    "<b5>====== Команды Docker ======</>",
    " <c3>lim go <контейнер></>",
    "  Создает скрипты для перехода в директорию контейнера.",
    " <c3>lim inspect <контейнер></>",
    "  Показывает 'docker inspect'.",
    "",
    "<b5>====== Закладки (Телепорт) ======</>",
    " <c3>lim tp <имя_закладки></>",
    "  Создает скрипты для перехода по закладке.",
    " <c3>lim tp list</>",
    "  Показывает все закладки.",
    "",
    "<c5>Нажмите [m] для полной справки по CLI</>",
]

HELP_CLI_DETAILED_TITLE = "Детальная справка по CLI командам"
HELP_CLI_DETAILED = [
    "lim",
    "  - Запускает главный TUI-монитор системы.",
    "lim tui (или list, nav, l)",
    "  - Запускает навигационный TUI для Docker и закладок.",
    "",
    "--- Docker ---",
    "lim go <имя_или_id>",
    "  - Создает временные скрипты (l.sh, b.sh) для перехода в директорию docker-compose контейнера.",
    "lim inspect <имя_или_id>",
    "  - Показывает результат 'docker inspect' для контейнера.",
    "lim updatecache",
    "  - Принудительно обновляет кэш контейнеров Docker (~/.config/lim/docker_cache.json).",
    "",
    "--- Закладки (Телепорт) ---",
    "lim tp <имя>",
    "  - Создает скрипты (l.sh, b.sh) для перехода в директорию, сохраненную в закладке.",
    "lim tp list",
    "  - Показывает таблицу со всеми созданными закладками.",
    "lim tp add <имя> [путь]",
    "  - Добавляет новую закладку. Если путь не указан, используется текущая директория.",
    "lim tp del <имя>",
    "  - Удаляет закладку с указанным именем.",
]